"""empty message

Revision ID: 92881dc77101
Revises: 13e8d0e8ccb1
Create Date: 2019-03-04 19:29:03.468067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92881dc77101'
down_revision = '13e8d0e8ccb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('first_name', sa.String(length=90), nullable=False))
    op.add_column('person', sa.Column('nickname', sa.String(length=90), nullable=False))
    op.drop_constraint('person_username_key', 'person', type_='unique')
    op.create_unique_constraint(None, 'person', ['nickname'])
    op.create_unique_constraint(None, 'person', ['id'])
    op.drop_column('person', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('username', sa.VARCHAR(length=90), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'person', type_='unique')
    op.drop_constraint(None, 'person', type_='unique')
    op.create_unique_constraint('person_username_key', 'person', ['username'])
    op.drop_column('person', 'nickname')
    op.drop_column('person', 'first_name')
    # ### end Alembic commands ###
