"""empty message

Revision ID: b8d1618092c3
Revises: 92881dc77101
Create Date: 2019-03-04 19:43:32.086708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8d1618092c3'
down_revision = '92881dc77101'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('second_name', sa.String(length=90), nullable=True))
    op.drop_column('person', 'first_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('first_name', sa.VARCHAR(length=90), autoincrement=False, nullable=False))
    op.drop_column('person', 'second_name')
    # ### end Alembic commands ###
